# Shell variables
# Generated by 'wal'
wallpaper='/home/uriel/.config/polybar/wallpapers/girl.jpg'

# Special
background='#121212'
foreground='#dad6d2'
cursor='#dad6d2'

# Colors
color0='#121212'
color1='#746B68'
color2='#924D37'
color3='#867972'
color4='#867F7F'
color5='#91847B'
color6='#978E8B'
color7='#dad6d2'
color8='#989593'
color9='#746B68'
color10='#924D37'
color11='#867972'
color12='#867F7F'
color13='#91847B'
color14='#978E8B'
color15='#dad6d2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
